---
title: "DSOM 5509 -- Applied Statistical Methods"
author: "Spring 2019"
output: 
  html_document: 
    fig_height: 4.5
    fig_width: 6.5
    theme: cosmo
    toc: yes
    toc_float: yes
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

### Course Description

This course Investigates the use of sample data for purposes of estimating, predicting, forecasting and explaining correlations among varied observations. Students will apply the concepts of probability theory, central tendency, sampling, inference, modeling and forecasting to help solve managerial problems and to support decision processes. This course also provides students with an understanding of the role data plays in today's organizations. Because business analytics has become a key component in accomplishing strategic and operational goals, students will become familiar with the concepts and principles of business analytics to support managerial decision making.

#### Course Purpose

*Learn from your data, but your data should not be your teacher.* ~ Rex Kline

Statistics is not a subject that many students long to take. Many of you may have already had a statistics course as an undergraduate that, to put it politely, left you dissatisfied (as in you could not wait for the class to be over!).  

If that’s the case, I’m hoping that you have a different experience in this class.

I am passionate about data science and its power to enhance decision making in organizations---and in your personal life, for that matter. While there is growing interest and recognition in the power of data science for business, and a commensurate growth of tools available to conduct large scale analysis, the fundamentals of applied statistics remain much the same as they have been for decades. This is our focus---learning the fundamentals that apply whether you are looking at a correlation or a negative binominal regression. More importantly though, we'll be talking about how to best integrate data science into your decision making, how to be a better consumer of statistical analysis products, and how to better manage research and data science projects.  This is a foundations course, and one that will provide a valuable knowledge base during your time at Bloch and beyond. 

The underlying goal of a good data science course is to improve your ability to think statistically. Our goal is is to understand probability, to identify meaningful questions, to tease out potential solutions to these problems, and to use those insights to make better decisions and predictions. This is fundamentally a dynamic process that unfolds under uncertainty---there will always be an element of randomness to our analyses and to how the world unfolds around us. That means data science has more than a little ‘art’ to its (useful) practice!

If you are willing to be a little uncomfortable, if you are willing to accept that statistics is not as black and white as you might think, and if you are willing to think a little more like a scientist when you approach data and analyses, then I believe this will be one of the funnest courses of your tenure at the Bloch School.

*The data may not contain the answer. The combination of some data and an aching desire for an answer does not ensure that a reasonable answer can be extracted from a given body of data.* ~ John Tukey

#### Course Learning Objectives

| Executive MBA SLOs | DSOM 5509 SLOs |
|:-------------------------------|:-------------------------------|
| **Strategic Perspective and Business Acumen:** Students will apply strategic frameworks to complex business issues and identify viable options and forward-looking strategies, through the integrated analysis of multiple functional perspectives – e.g. marketing, product development/service delivery, finance, operations and human capital. | Students will demonstrate sound reasoning and effective decision making through the use of statistical methods, tools, and analytical thinking. |
| **Public Policy Awareness:** Students will demonstrate enhanced understanding of complex public sector systems, processes and leaders, and identify and define the various forces that shape and impact business policy. |  |
| **Innovative Mindset:** Students will demonstrate the skills needed to generate creative solutions that address unmet needs and wants, evaluate the relative attractiveness of competing solutions, and organize to exploit opportunities in the marketplace. | Students will apply statistical and analytical methods to resolve issues and approach new business opportunities. |
| **Global Perspective:** Students will utilize a knowledge framework to 1) critically think about and assess the impact and linkage of global influences, issues, trends, and decisions in business models; and 2) demonstrate insight and agility in operating within a global business environment. |  |
| **Teamwork:** Students will demonstrate the communication and interpersonal skills needed for effective collaboration and creative problem-solving, as well as the versatility to add value in a variety of team roles – leader, expert, facilitator, etc. | Students will demonstrate their ability to collectively and collaboratively research, present and solve business issues, while using data and statistical thought to identify business opportunities. |
| **Strategic Leadership:** Students will demonstrate the ability to 1) diagnose complex business situations, recognizing key issues, tensions and dilemmas; and 2) articulate decisions and action plans that reflect comprehensive understanding of the human, political, and cultural context as well as nuanced ways of building influence and support. | Students will demonstrate their understanding of applying data and analytics to the strategic planning process. |

#### Class Format

This is not a traditional lecture-based course. I use a modified version of the ‘flipped classroom’ format, which means that you will read blog posts, academic papers, watch a video before each period, and complete an assessment exercise. During class we will focus on solving a problem or problems using exercises, team activities, additional assessments, and an open discussion. Success in this course is a function of your engagement. I cannot stress this point enough--you must engage with the material and with your peers. Data science is a contact sport---you must come to each and every class prepared and ready to contribute!

<br>

***

### Course Materials

In addition to the books, blogs, and other resources listed below, you can find all of the readings available through the [UMKC Library](https://library.umkc.edu/mnl), [Google Scholar](https://scholar.google.com/) (for off-campus access, I encourage you to use the [UMKC VPN service](http://www.umkc.edu/is/support/services/VPN/)), or direct link in this document.  Please remember to bring a laptop to each session.  You will also need to have [R version 3.4.3 or higher](https://cran.r-project.org/) and [RStudio 1.1.383 or higher](https://www.rstudio.com/products/rstudio/download/#download) installed on your laptop.

We will use the [RDTT IV Spring 2018](https://rdttivspring2018.slack.com/) Slack workspace as our primary course management system, along with our [RDTT IV Organization](https://github.com/RDTT-IV) on GitHub.

#### Books

* [Happy Git and GitHub for the useR](http://happygitwithr.com)
* [R for Data Science](http://r4ds.had.co.nz)
* [Data Visualization for Social Science](http://socviz.co)
* [Text Mining with R](https://www.tidytextmining.com)

The following books are not obligatory, but highly recommended.  Recommended in the sense that they should (will) become a valuable part of your scholarly library.  I will not use these books specifically in our class discussions, but may refer you to them for additional information.

* Angrist J, Pischke J-S. 2008. Mostly Harmless Econometrics: An Empiricist’s Companion. Princeton University Press: Princeton, NJ.
* Dubin R. 1978. Theory Building (2nd Edition). New York: Free Press.
* Popper K. 2002. The Logic of Scientific Discovery (2nd Edition). Routledge: London.
* Morgan SL, Winship C. 2007. Counterfactuals and Causal Inference: Methods and Principles for Social Research. Cambridge University Press: New York.
* Gelman A et al. 2013. Bayesian Data Analysis (3rd Edition). CRC press: Boca Raton, FL.
* Cook TD, Campbell DT. 1979. Quasi-Experimentation: Design and Analysis Issues for Field Settings. Houghton Mifflin: Boston, MA.
* Cohen J, Cohen P, West SG, Aiken LS. 2003. Applied Multiple Regression/Correlation Analysis for the Behavioral Sciences. Erlbaum: Maywah, NJ.
* Bollen KA. 1989. Structural Equations with Latent Variables. John Wiley: New York.
* Wooldridge JM. 2010. Econometric Analysis of Cross Section and Panel Data. MIT Press: Cambridge, MA.

#### Blogs

* [Mine!](http://www.drbanderson.com)
* [Retraction Watch](http://retractionwatch.com)
* [DataColada](http://datacolada.org)
* [Andrew Gelman's Blog](http://andrewgelman.com)
* [Simply Statistics](http://simplystatistics.org)

#### R and Related Resources 

* [How to use the rstanarm package](https://cran.r-project.org/web/packages/rstanarm/vignettes/rstanarm.html)
* [GitHub documents with R Markdown](http://rmarkdown.rstudio.com/github_document_format.html)
* [Using Skimr](https://cran.r-project.org/web/packages/skimr/vignettes/Using_skimr.html)
* [Creating HTML tables with knitr::kable and kableExtra](https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html)
* [The `lavaan` project](http://lavaan.ugent.be/)
* [Visualizing missing data with naniar](http://naniar.njtierney.com/articles/getting-started-w-naniar.html)
* [Table of Conjugate Priors](https://en.wikipedia.org/wiki/Conjugate_prior#Table_of_conjugate_distributions)

<br>

***
### Course Schedule

To Be Added

<br>

***
### Assessment

#### Assessment Breakdown

* Attendance & Participation: 30%
* Lab Exercises: 20%
* Study Preregistration: 50%

#### Attendance & Participation

From a pedagogical perspective, we maximize student comprehension when we combine reading materials, performing experiential activities, and discussion with peers.  Readings are a required element for classroom participation, and experiential activities happen in the lab and through the large proposal project.  That means discussion is our third critical assessment mechanism, and it takes your active involvement, preparation, and participation to add value to all of us.  This is not, however, an MBA class where you are competing for ‘airtime.’  We are scholars and scientists, and discussion is an important way in which we communicate and improve our work.  My expectation is that you will meaningfully contribute to each class session by engaging in our conversations and by asking--and answering--questions.  Yes, I will cold-call if you are not meeting this expectation.  The easiest way to lose points is to be demonstrably unprepared or to behave in a rude, unprofessional manner.  I have every expectation however that you will earn the maximum points available for this assessment.  

#### Lab Exercises

During most lab sessions, we will have a brief assessment exercise.  Most often these will be completion exercises that you finish during that session, and that we will debrief that day.  

#### Study Pregistration

The main deliverable in the class will be a study preregistration, accompanied by any necessary [UMKC Institutional Review Board](http://ors.umkc.edu/research-compliance-(iacuc-ibc-irb-rsc)/institutional-review-board-(irb)) approval. We will cover the specific deliverable requirements in a Lab Session on 8 Feb, and please see the course schedule for deliverable due-dates.

#### Grading Scale

| Grade | Evaluation | Min. Percent |
| ---- | ---------------- | --- |
| A | Superior/Excellent | 93 |
| A- |   | 90 |
| B+ |   | 87 |
| B | Good/Above Average | 83 |
| B- |   | 80 |
| C+ |   | 77 |
| C | Competent/Average | 73 | 
| C- |   | 70 |
| D+ |   | 67 |
| D | Minimum Passing | 63 |
| D- |   | 60 |
| F | Failing | <60 |

<br>

***
### Course Logistics

| About the... | Details... |
|:---------------|:-------------------------------------------------------|
| Class Sessions | [EMBA course calendar](https://bloch3.umkc.edu/wp-content/uploads/2018/03/Recruiting-Calendar.pdf) | 
| Office Hours | By appointment. |
| Catalog Info | DSOM 5509---Applied Statistical Methods |
| Credit Hours | 2 |
| Prerequisites | Student must be enrolled in the Executive MBA program and in good academic standing. |
| Restrictions | This class is not open to students who are not enrolled in the Executive MBA program. |
| Course Format | Recitation/seminar/discussion | 
| Instructional Mode | Classroom based |
  
<br>

***
### UMKC Support Services

| Topic... | Services... |
|:---------------|:-------------------------------------------------------|
| Technology Support | [Online](https://www.umkc.edu/IS/comments_or_problems.asp), [Helpdesk Chat](https://home-c6.incontact.com/inContact/ChatClient/ChatClientPatron.aspx?poc=f82230de-b694-4fa2-9678-febda492d489&bu=4593164), p(816-235-6700), email: callcenter@umkc.edu |
| UMKC Alert | [Sign up for the UMKC Alert Emergency Information Center](https://www.umkc.edu/umkcalert/default.asp) to receive real-time updates on severe weather, medical emergency, fire, chemical spill, evacuation, unauthorized persons, police emergency, radioactive release, flood, earthquake, tornado warning, bomb threat, and active shooter. |
| Police Department | The fundamental mission of the University Police force is to provide the leadership and professional support required to sustain and improve the University System’s efforts to develop a balanced police-University community effort against any lawlessness or disorderly conduct which could interfere with the general missions of the University System. As such, the [UMKC Police Department](https://www.umkc.edu/finadmin/police/default.asp) is an essential university partner promoting a safe and orderly learning environment and enhanced quality of life with a reduction of crime, social disorder and fear of crime. |
| Disability Services | To obtain disability related accommodations and/or auxiliary aids, students with disabilities must contact the [Office of Services for Students with Disabilities](https://info.umkc.edu/disability-services/) (OSSD) as soon as possible. To contact OSSD, call (816) 235-5696 or email at disability@umkc.edu. You may also visit the office in-person at 5110 Oak Street, Suite 225, Monday-Friday from 8:30-5:00. Once verified, OSSD will notify the course instructor and outline the accommodation and/or auxiliary aids to be provided. |

<br>

***
### Classroom Policies

| Topic... | Policy... |
|:---------------|:-------------------------------------------------------|
| Syllabus Changes | While it is my intention to adhere to the class-by-class schedule and list of deliverables set forth in in the syllabus, I reserve the right to make changes for pedagogical or other compelling reasons.  Any significant changes will be announced in class, sent over UMKC email, and in this syllabus. |
| UMKC Mission | UMKC’s mission is to lead in life and health sciences; to deepen and expand strength in the visual and performing arts; to develop a professional workforce and collaborate in urban issues and education; and to create a vibrant learning and campus life experience. |
| Academic Honesty | The Board of Curators of the University of Missouri recognizes that academic honesty is essential for the intellectual life of the University. Faculty members have a special obligation to expect high standards of academic honesty in all student work. Students have a special obligation to adhere to such standards. Academic dishonesty, including cheating, plagiarism or sabotage, is adjudicated through the [University of Missouri Student Conduct Code](http://www.umsystem.edu/ums/rules/collected_rules/programs/ch200) and [Rules of Procedures in Student Conduct Matters](https://www.umsystem.edu/ums/rules/collected_rules/programs/ch200/200.020_rules_of_procedures_in_student_conduct_matters). The University of Missouri outlines Student Conduct expectations and sanctions for violations, including academic dishonesty (like plagiarism and cheating).  For more information see: [University of Missouri Student Conduct Code.](http://www.umsystem.edu/ums/rules/collected_rules/programs/ch200/200.010_standard_of_conduct) |
| Academic Calendar | The University has very specific guidelines on withdrawing from classes.  There are important financial and assessment implications of trying to drop a course after the deadline. You can find registration, drop, and withdrawal dates through the [Registrar’s Registration and Records website.](https://www.umkc.edu/Registrar/registration/registration-dates.asp) |
| Academic Inquiry, Course Discussion, and Privacy | University of Missouri System Executive Order No. 38 lays out principles regarding the sanctity of classroom discussions at the university. The policy is described fully in Section 200.015 of the Collected Rules and Regulations. In this class, students may make audio or video recordings of course activity unless specifically prohibited by the faculty member. However, the redistribution of any audio or video recordings of statements or comments from the course to individuals who are not students in the course is prohibited without the express permission of the faculty member and of any students who are recorded, including those recordings prepared by an instructor. Students found to have violated this policy are subject to discipline in accordance with provisions of Section 200.020 of the Collected Rules and Regulations of the University of Missouri pertaining to student conduct matters. |
| Attendance Policy | Students are expected to attend and participate in classes and lab sessions. **Given the unique nature of the EMBA program, missing a class or lab session should occur in emergency situations only.** |
| English Proficiency Statement | Students who encounter difficulty in their courses because of the English proficiency of their instructors should speak directly to their instructors. If additional assistance is needed, they may contact the UMKC Help Line at 816-235-2222 for assistance. |
| Grade Appeal Policy | Students are responsible for meeting the standards of academic performance established for each course in which they are enrolled. The establishment of the criteria for grades and the evaluation of student academic performance are the responsibilities of the instructor. This grade appeal procedure is available only for the review of allegedly capricious grading and not for review of the instructor's evaluation of the student's academic performance. Capricious grading, as that term is used here, comprises any of the following: a) The assignment of a grade to a particular student on some basis other than the performance in the course; b) The assignment of a grade to a particular student according to more exacting or demanding standards than were applied to other students in the course; (Note: Additional or different grading criteria may be applied to graduate students enrolled for graduate credit in 300- and 400-level courses.); c) The assignment of a grade by a substantial departure from the instructor's previously announced standards. |
| Grievance procedures | The University will promptly and appropriately respond to any complaint of violation of the University’s anti-discrimination policies. [The procedures described in the UM System Rules and Regulations](https://www.umsystem.edu/ums/rules/collected_rules/equal_employment_educational_opportunity/ch600) apply to such complaints. |
| Notice of Non-Discrimination | UMKC does not discriminate on the basis of race, color, ethnic or national origin, sex, sexual orientation, gender identity, religion, age, ancestry, disability, military status, veteran status, in admissions, educational programs or activities and employment. The University complies with all federal and state laws and [University of Missouri Statement of Nondiscrimination](https://missouri.edu/statements/eeo-aa.php) including Title IX of the Education Amendments of 1972, Section 504 of the rehabilitation Act of 1973, Title VII of the Civil Rights Act of 1964 and the state of Missouri Human Rights Act Chapter 213 RSMO. |
| Sex Discrimination, Harassment, and Assault | [Title IX of the Education Amendments of 1972](https://info.umkc.edu/title9/about/) is a federal law that prohibits sex discrimination in education. It reads, “No person in the United States shall, on the basis of sex, be excluded from participation in, be denied the benefits of, or be subjected to discrimination under any education program or activity receiving Federal Financial Assistance” -Title IX of the Education Amendments of 1972, and its implementing regulations at 34 C. F. R. Part 106. Sex discrimination includes sexual harassment, assault, and/or violence. Title IX is often thought of as the law that applies to athletic programs, Title IX is much broader than Athletics and applies to all programs at UMKC. While compliance with the law is everyone’s responsibility at UMKC, you can find a list of staff members below who have primary responsibility for Title IX compliance. |
| Statement of Human Rights | The Board of Curators and UMKC are committed to the policy of equal opportunity, regardless of race, color, religion, sex, sexual orientation, national origin, age, disability and status as a Vietnam era veteran. Commitment to the policy is mentored by the [Division of Diversity, Access & Equity](https://www.umkc.edu/diversity/), but it is the responsibility of the entire university community to provide equal opportunity through relevant practices, initiatives and programs. |
  
<br>

***
<center>
*Three statisticians go hunting.  The first one shoots, and misses far right.  The second one shoots, and misses far left.  The third one says, "we got it!"*
</center>

***
<small>
<center>
Brian S. Anderson, Ph.D. | Associate Professor of Entrepreneurship | andersonbri@umkc.edu  
Henry W. Bloch School of Management | University of Missouri - Kansas City  
**[entrepreneurship.bloch.umkc.edu](http://www.entrepreneurship.bloch.umkc.edu)**  
(c) Brian S. Anderson, 2019  
</center>
</small>

